//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ticket")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub swimlane_id: i32,
    pub name: String,
    pub description: String,
    pub start_at: Option<DateTime>,
    pub end_at: Option<DateTime>,
    pub priority: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::swimlane::Entity",
        from = "Column::SwimlaneId",
        to = "super::swimlane::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Swimlane,
}

impl Related<super::swimlane::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Swimlane.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
